// PORT=3000
// NODE_ENV='development'
// APP_ID=''

// JWT_PUBLIC_KEY_PATH=''
// DISABLE_AUTHENTICATION=''

// APP_CMDB_ID=''
// APP_SERVICE_NAME=''
// REDACT_PATHS=''
// LOG_LEVEL=''

// MONGO_CONNECTION_TIMEOUT = 30000
// MONGO_CONNECTION_STRING=''
// MONGO_USER=''
// MONGO_HOST=''
// MONGO_PORT=''
// MONGO_DBNAME=''
// MONGO_COLLECTION=''
// MONGODB_PASSWORD=''

// MONGO_SSL_KEY=''
// MONGO_SSL_CRET=''
// MONGO_CA_PEM=''
// MONGO_REPLICASET=''
// MONGO_AUTH_SOURCE=''
// MONGO_AUTH_MECHANISM=''

// REQUEST_LIMIT='100kb'
// SESSION_SECRET=''

// CONSUMER_BROKER=''
// CONSUMER_CLIENT_ID=''
// CONSUMER_GROUP_ID=''
// CONSUMER_TOPIC=''

// PRODUCER_BROKER=''
// PRODUCER_CLIENT_ID=''

// CERT=''
// KEY=''
// CA=''
// ENRICHMENT_HOST=''
// ENRICHMENT_URL_PATH=''
